### ISSUE TITLE
How to generate the pix_private_key from dashboard or download it?

### ISSUE THREAD

**Issue by franciscoalienos** [gerencianet/gn-api-sdk-dart#11]

**Comment by guilhermecotaGn** [comment]
Hello, @franciscoalienos.

For use in Dart, the certificate must be converted to `.pem`, separated into two files. [Here you will find an example of using the OpenSSL command for conversion](https://github.com/gerencianet/gn-api-sdk-dart#command-openssl).

If you have any further questions, please contact us on our [Discord server](https://discord.gg/ptGHMtczcV) as well.
