### ISSUE TITLE
Não contempla o getPaymentToken ??

### ISSUE THREAD

**Issue by ranulfo** [gerencianet/gn-api-sdk-dart#19]
Boa tarde, Pessoal.
Consegui utilizar, por exemplo, o método "call" com o endPoint "getInstallments" com sucesso. Porém, ao utilizar o endPoint "getPaymentToken", recebo o erro:
   `Unhandled Exception: Exception: nonexistent endpoint`
Provavelmente este endPoint não foi contemplado no SDK e a minha intenção é utilizar o flutter mobile e não o flutter web e a integração flutter + webView + javascript é muito chata e não estou obtendo sucesso.
Há uma previsão para contemplar este método no SDK ou alguma alternativa de como chamar o JS do GN no flutter de forma clara ?
Desde já agradeço.

**Comment by ranulfo** [comment]
Debugando o código com mais atenção, ví que o endpoint no flutter não tem o mesmo nome do JS e é apenas "paymentToken".
No entanto, ao testa-lo, recebo um null exception:

`Unhandled Exception: type 'Null' is not a subtype of type 'Object'`
`PaymentToken.getTokenizer (package:gerencianet/src/payment_token.dart:38:47)`

Analisando a linha 38 do arquivo payment_token.dart, vejo que o trecho de código é o seguinte:

`request.headers.add('account-code', config['accountId']);`

Provavelmente o array `config['accountId']`está vindo nulo, há algum problema com meu accountId ?
lembrando que eu consegui chamar o endPoint "getInstallments" com sucesso.

**Comment by ranulfo** [comment]
Nessa caso, era o nome da variável account_id e não accountId

**Comment by iigorpedroso** [comment]
@ranulfo, boa tarde!
A geração do payment token só possível na versão 1.2.0 ou superior. 
Além de estar atualizado, você precisa adicionar o atributo "account_id" com o seu Identificador de Conta na variável que armazena as suas credenciais (client_id e client_secret).
